import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Login from './login'
import Premiumfeatures from './premiumfeatures'
import Activities_tabs from '../components/homepage/activities_tabs'
import Activities from './activities'
import Stream_statistics from './stream_statistics'

export default function Home() {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login />
      {/* <Premiumfeatures/> */}
      {/* <Activities_tabs/> */}
      {/* <Activities/> */}
      {/* <Stream_statistics/> */}

    
    </div>
  )
}
