import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Login from './login'
import Premiumfeatures from './premiumfeatures'
import Activities_tabs from '../components/homepage/activities_tabs'
import Activities from './activities'
import Stream_statistics from './stream_statistics'
import Stream_statistics_enable from './stream_statistics_enable'
import Statistics_unlockpremium from './statistics_unlockpremium'
import Stream_preview from './stream_preview'
import Unlockpremiumfeatures from './unlockedpremiumfeatures'
import Enablepremiumfeatures from './enablepremiumfeatures'
import Stream_premiumenable from './stream_premiumenable'
import Stream_unlockfeatures from './stream_unlockfeatures'
import Settings from './settings'



export default function Home() {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Login /> */}
      <Settings/>
      {/* <Premiumfeatures/> */}
      {/* <Activities_tabs/> */}
      {/* <Activities/> */}
      {/* <Stream_statistics/> */}
      {/* <Stream_statistics_enable/> */}
      {/* <Statistics_unlockpremium/> */}
      {/* <Stream_preview/> */}
      {/* <Unlockpremiumfeatures/> */}
      {/* <Enablepremiumfeatures/> */}
      {/* <Stream_premiumenable/> */}
      {/* <Stream_unlockfeatures/> */}
    </div>
  )
}
